python $woxPluginsDev/deploy.py --plugin-name (Get-Item -Path ".\").Name --filename "main.py"
python $woxPluginsDev/deploy.py --plugin-name (Get-Item -Path ".\").Name 
python $woxPluginsDev/deploy.py --plugin-name (Get-Item -Path ".\").Name --package
python deploy.py
python deploy.py "just main.py"
start https://github.com/Doist/todoist-python/issues/39 # api usage sample
start https://github.com/Doist/todoist-python/blob/master/tests/test_api.py # api tests
start https://github.com/Wox-launcher/Wox # wox github
start https://github.com/Garee/pytodoist